INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (100, 'Ninjas');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (101, 'Family Matters');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (102, 'Rocking Family');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (103, 'Good of Times, Bad of Times');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (104, 'Republic of Restless');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (105, 'The Chicken Tenders');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (106, 'Modern Family');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (107, 'Superstar Family');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (108, 'Crazy World');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (109, 'Devils Vs Angels');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (110, 'Unfired');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (111, 'Ignorant Buddies');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (112, 'Spicy Sugars');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (113, 'Lords of the Bling');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (114, 'Seven Smokers');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (115, 'The Alter Egos');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (116, 'The Badasses');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (117, 'Silence is our enemy');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (118, '‘Sup Group');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (119, 'Phone Pals');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (120, 'Weird Clicks');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (121, 'Non-Stop Pings');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (122, 'The Uncalled Four');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (123, 'Cutest Family');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (124, 'Lords of the Bling');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (125, 'Fantastic 4');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (126, 'Unique Group Names List');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (127, 'Tough Team');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (128, 'Unfired');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (129, 'Strong Bonding');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (130, 'Study Buddies');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (131, 'My Family');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (132, 'The Family Gang');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (133, 'Spicy Sugars');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (134, 'Non-Stop Pings');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (135, 'Superstar Family');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (136, 'Lords of the Bling');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (137, 'The Cool Nerds');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (138, 'chatter Box');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (139, 'Fantastic 4');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (140, 'The Cool Nerds');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (141, 'The Badasses');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (142, 'Wonderring Minds');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (143, 'Modern Family');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (144, 'Ignorant Buddies');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (145, 'Pretty Family');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (146, 'Savages');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (147, 'Colonial Cousins');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (148, 'Lords of the Bling');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (149, 'Family Matters');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (150, 'Savages');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (151, 'Trolls of disgust');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (152, 'Childhood Chilkuts');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (153, 'chatter Box');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (154, 'The Chicken Tenders');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (155, 'Family Matters');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (156, 'Tech Ninjas');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (157, 'The Uncalled Four');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (158, 'Superstar Family');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (159, 'The Badasses');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (160, 'Devils Vs Angels');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (161, 'Ignorant Buddies');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (162, 'The Family Gang');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (163, 'Black Panthers');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (164, 'The Family Gang');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (165, '‘Sup Group');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (166, 'Devils Vs Angels');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (167, 'Silence is our enemy');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (168, 'Spicy Sugars');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (169, 'Sports lovers');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (170, 'Sports lovers');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (171, 'My Family');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (172, 'Don’t spoil it');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (173, 'Silence is our enemy');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (174, 'Recycle Bin');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (175, 'The Uncalled Four');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (176, 'Superstar Family');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (177, 'The Badasses');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (178, 'The Uncalled Four');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (179, 'Country’s future weapons');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (180, 'All Us Single Ladies');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (181, 'Country’s future weapons');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (182, 'Rocking Family');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (183, 'Superstar Family');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (184, 'Changing Majors');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (185, 'Tough Team');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (186, 'Childhood Chilkuts');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (187, '404! Group name does not exist');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (188, 'Dolls With Balls');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (189, 'Non-Stop Pings');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (190, 'The Uncalled Four');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (191, 'Seven Smokers');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (192, 'Wrong Numbers');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (193, 'Weird Clicks');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (194, 'Ninjas');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (195, 'Superstar Family');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (196, 'Banish Gang');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (197, 'Weird Clicks');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (198, 'The So and So');
INSERT INTO `Chat_session` (`Session_id`, `Chat_name`) VALUES (199, 'Unfired');
